version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: usersdb-dev
    environment:
      POSTGRES_DB: users_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
volumes:
  postgres_dev_data:
